# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

# Mod properties
maven_group = com.skyraax
mod_id = logisticmatica
mod_name = Logisticmatica
mod_file_name = logisticmatica-fabric
mod_version = 0.1.0-dev

# Litematica ecosystem dependency versions (sakura-ryoko maven)
malilib_version = 0.29.3
litematica_version = 0.28.3

# Minecraft / Fabric versions
minecraft_version = 26.2
minecraft_version_out = 26.2
fabric_loader_version = 0.19.3
fabric_api_version = 0.152.1+26.2

# Extra libraries
fabric_permissions_api_version = 0.7.0
mod_menu_version = 20.0.0-beta.2
